name : Auto commit to repository

on:
    schedule:
      - cron: '3 6,8,17 * * 0-2'
      - cron: '0 10-21 * * 1-5'
      - cron: '10 2-22 3-26 1-6 1-5'
      - cron: '19 8 * * *'

jobs:
    auto_commit:
      name: 'Auto push a commit to my repo'
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Create file with just timestamp
        run: date +%s >> data.txt
      - name: Commit file
        run: |
            git config --global user.name 'Isaac'
            git config --global user.email 'isaacnguyen8998'
            git add data.txt
            git commit -m "Automated changed"
            git push
    
    
    
